apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"backend","namespace":"default"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"backend"}},"template":{"metadata":{"labels":{"app":"backend"}},"spec":{"containers":[{"env":[{"name":"DATABASE_URL","valueFrom":{"secretKeyRef":{"key":"database_url","name":"secrets"}}},{"name":"GOOGLE_CLIENT_ID","valueFrom":{"secretKeyRef":{"key":"google_client_id","name":"secrets"}}},{"name":"GOOGLE_CLIENT_SECRET","valueFrom":{"secretKeyRef":{"key":"google_client_secret","name":"secrets"}}},{"name":"JWT_SECRET","valueFrom":{"secretKeyRef":{"key":"jwt_secret","name":"secrets"}}},{"name":"OAUTH_CALLBACK_URL","value":"https://hnstation.dev/auth/google/callback"},{"name":"FRONTEND_URL","value":"/"},{"name":"OLLAMA_URL","value":"http://ollama:11434"}],"image":"myhnregistry270.azurecr.io/backend:latest","imagePullPolicy":"Always","name":"backend","ports":[{"containerPort":8080}],"resources":{"limits":{"cpu":"250m","memory":"256Mi"},"requests":{"cpu":"100m","memory":"128Mi"}},"volumeMounts":[{"mountPath":"/mnt/secrets-store","name":"secrets-store-inline","readOnly":true}]}],"volumes":[{"csi":{"driver":"secrets-store.csi.k8s.io","readOnly":true,"volumeAttributes":{"secretProviderClass":"azure-kv"}},"name":"secrets-store-inline"}]}}}}
  creationTimestamp: "2026-03-30T05:11:49Z"
  generation: 2
  name: backend
  namespace: default
  resourceVersion: "2812900"
  uid: 21791487-59b6-4b5d-bdc5-87059bf47bad
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2026-03-30T10:42:05+05:30"
      creationTimestamp: null
      labels:
        app: backend
    spec:
      containers:
      - env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              key: database_url
              name: secrets
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: google_client_id
              name: secrets
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: google_client_secret
              name: secrets
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              key: jwt_secret
              name: secrets
        - name: OAUTH_CALLBACK_URL
          value: https://hnstation.dev/auth/google/callback
        - name: FRONTEND_URL
          value: /
        - name: OLLAMA_URL
          value: http://ollama:11434
        image: myhnregistry270.azurecr.io/backend:latest
        imagePullPolicy: Always
        name: backend
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /mnt/secrets-store
          name: secrets-store-inline
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: azure-kv
        name: secrets-store-inline
status:
  conditions:
  - lastTransitionTime: "2026-03-30T05:11:49Z"
    lastUpdateTime: "2026-03-30T05:11:49Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2026-03-30T05:21:58Z"
    lastUpdateTime: "2026-03-30T05:21:58Z"
    message: ReplicaSet "backend-7fb4f6d99b" has timed out progressing.
    reason: ProgressDeadlineExceeded
    status: "False"
    type: Progressing
  observedGeneration: 2
  replicas: 3
  unavailableReplicas: 3
  updatedReplicas: 1
