apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-sync-sidecar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-sync
  template:
    metadata:
      labels:
        app: secret-sync
    spec:
      nodeSelector:
        agentpool: aipool
      containers:
      - name: pause
        image: registry.k8s.io/pause:3.9
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kv"
