apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv
spec:
  provider: azure
  secretObjects:
  - secretName: secrets
    type: Opaque
    data:
    - objectName: database-url
      key: DATABASE_URL
    - objectName: password
      key: password
    - objectName: google-client-id
      key: GOOGLE_CLIENT_ID
    - objectName: google-client-secret
      key: GOOGLE_CLIENT_SECRET
    - objectName: jwt-secret
      key: JWT_SECRET
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "ad90a674-6d8d-43e2-96d8-ad883c1479e4"
    keyvaultName: "my-hn-kv-22139"
    cloudName: ""
    objects: |
      array:
        - |
          objectName: database-url
          objectType: secret
        - |
          objectName: password
          objectType: secret
        - |
          objectName: google-client-id
          objectType: secret
        - |
          objectName: google-client-secret
          objectType: secret
        - |
          objectName: jwt-secret
          objectType: secret
    tenantId: "d3c187bb-f433-492a-8866-6aca0c938873"
