# Azure AKS secrets — NOT safe to commit real values here.
# In production these are sourced from Azure Key Vault via the Secrets Store CSI driver.
# These placeholders match the keys expected by the Azure manifests in this directory.
apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
data:
  # postgres://hn_user:rootPass1@postgres:5432/my_hn?sslmode=disable
  password: REPLACE_WITH_BASE64_PASSWORD
  database_url: REPLACE_WITH_BASE64_DATABASE_URL
  google_client_id: REPLACE_WITH_BASE64_GOOGLE_CLIENT_ID
  google_client_secret: REPLACE_WITH_BASE64_GOOGLE_CLIENT_SECRET
  jwt_secret: REPLACE_WITH_BASE64_JWT_SECRET
